#!/usr/bin/env python3
"""Writes site/art.js from CatFrames.swift and PixelFont.swift, so the site
draws the same cat and the same letters as the app. Run it after
make-sprites.py, or after the font changes."""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
render = root / "Sources/AwayBlur/Render"
frames = (render / "CatFrames.swift").read_text()
font = (render / "PixelFont.swift").read_text()

animations = []
for m in re.finditer(r'CatAnimation\(name: "(\w+)", fps: ([\d.]+), loops: (\w+), '
                     r'frames: (\d+)\.\.<(\d+), blink: (?:(\d+)\.\.<(\d+)|nil)', frames):
    name, fps, loops, a, b, ba, bb = m.groups()
    animations.append({"name": name, "fps": float(fps), "loops": loops == "true",
                       "frames": [int(a), int(b)],
                       "blink": [int(ba), int(bb)] if ba else None})
packed = re.findall(r'^\s*"([0-9a-f]{384})",?$', frames, re.M)
baseline = int(re.search(r"static let baseline = (\d+)", frames).group(1))

glyphs = {c: rows.split('", "') for c, rows in
          re.findall(r'^\s*"(.)": \["([.#", ]+)"\],$', font, re.M)}

cat = {"width": 48, "height": 32, "baseline": baseline,
       "animations": animations, "packed": packed}
(root / "site/art.js").write_text(
    "// Generated by Scripts/make-site-art.py from CatFrames.swift and PixelFont.swift. Do not edit.\n"
    f"export const CAT = {json.dumps(cat)};\n"
    f"export const FONT = {json.dumps(glyphs)};\n")
print(f"wrote site/art.js: {len(animations)} animations, {len(packed)} frames, {len(glyphs)} glyphs")
